FROM golang:alpine3.13

RUN go get -u github.com/cosmtrek/air

# COPY . /usr/src/app
WORKDIR /usr/src/app
# RUN cd tw-backend && go build -o /usr/src/app/test-back-app /usr/src/app/tw-backend/server.go
 
# CMD [ "go", "run", "server.go" ]